### ISSUE TITLE
Conflit between accessing raw_data attribute of Service and ServiceData

### ISSUE THREAD

**Issue by adnrs96** [storyscript/hub-sdk-python#23]
Currently if one follows the `README` instructions to get some info for a service, things don't work out as they are supposed to. We follow the instructions under Advanced usage section.

Trying to do this leads to error
```
python_service = StoryscriptHub(service_wrapper=True).get("python")
```

Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adnrs96/storyscript/venv-storyscript/lib/python3.6/site-packages/cachetools-3.1.0-py3.6.egg/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/home/adnrs96/storyscript/venv-storyscript/lib/python3.6/site-packages/story_hub-0.1.0-py3.6.egg/storyhub/sdk/StoryscriptHub.py", line 132, in get
    "service_data": json.loads(service.raw_data)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'method'
```

**Comment by adnrs96** [comment]
I believe if one takes a look at `storyhub/sdk/StoryscriptHub.py`
One would discover that this particular section is the cause of problem.

```python3
            assert isinstance(service, Service) or \
                isinstance(service, ServiceData)
            # if the service wrapper is set, and the service doesn't exist
            # we can safely convert this object since it was probably loaded
            # from the cache
            if wrap_service or self._service_wrapper is not None:
                return ServiceData.from_dict(data={
                    "service_data": json.loads(service.raw_data)
                })
```

I believe we should probably have checked if service is instance of ServiceData and immediately returned it. Something like this

```python3
            if wrap_service or self._service_wrapper is not None:
                if isinstance(service, ServiceData):
                    return service
                return ServiceData.from_dict(data={
                    "service_data": json.loads(service.raw_data)
                })
```
